data:
  input: 'titanic'
cols_definition:
  id_col: 'PassengerId'
  target_col: 'Survived'
preprocessing:
  delete_cols: ['Name', 'Ticket', 'PassengerId']
  label_encoding: ['Sex', 'Cabin', 'Embarked']
  aggregation:
    groupby_dict: [
      {
          'key': ['Sex'],
          'var': ['Age', 'Fare'],
          'agg': ['mean', 'sum', 'median', 'min', 'max', 'var', 'std']
      },
      {
          'key': ['Cabin'],
          'var': ['Age', 'Fare'],
          'agg': ['mean', 'sum', 'median', 'min', 'max', 'var', 'std']
      },
      {
          'key': ['Embarked'],
          'var': ['Age', 'Fare'],
          'agg': ['mean', 'sum', 'median', 'min', 'max', 'var', 'std']
      },
      {
          'key': ['Sex', 'Embarked'],
          'var': ['Age', 'Fare'],
          'agg': ['mean', 'sum', 'median', 'min', 'max', 'var', 'std']
      },
    ]
    nunique_dict: [
      {
          'key': ['Sex'],
          'var': ['Fare'],
          'agg': ['nunique']
      },
    ]
  matrix_factorization: ['Sex', 'Cabin', 'Embarked']
