name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install flake8 black mypy
      run:
        python -m pip install --upgrade pip
        pip install flake8 black mypy flake8-isort
    - name: Install for pytest
      run:
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install numpy==1.18.1
        pip install pandas==1.0.1
        pip install seaborn==0.10.0
        pip install scikit-learn==0.23.2
    - name: Lint with flake8
      run:
        flake8 . --max-line-length=99 --ignore=W503,E722
    - name: black
      run:
        black . --line-length 99 --exclude="docs"
    - name: mypy
      run:
        mypy --disallow-untyped-defs --ignore-missing-imports .
    - name: Test with pytest
      env:
        PYTHONPATH: /working
      run:
        pytest tests/ --cov=. --cov-report=html
